### ISSUE TITLE
error at installation

### ISSUE THREAD

**Issue by theoneandonly-vector** [EmpireProject/Empire-GUI#5]
system:
Kali light with Rolling repo's.

terminal:
npm install
npm WARN lifecycle empire-framework-gui@0.0.0~postinstall: cannot run in wd empire-framework-gui@0.0.0 electron-builder install-app-deps (wd=/opt/Empire-GUI)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 6.007s
[!] 16 vulnerabilities found [6029 packages audited]
    Severity: 7 Low | 7 Moderate | 2 Critical
    Run `npm audit` for more detail

when I run:
last few lines:

 DONE  Compiled successfully in 792ms                                                          5:03:28 PM

/opt/Empire-GUI/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by dchrastil** [comment]
This is a new one to me. Did you have any luck getting this to install? I will try to install it on Kali as well.

**Comment by theoneandonly-vector** [comment]
yeah somehow it works now..
