### ISSUE TITLE
password wrong?

### ISSUE THREAD

**Issue by gearcapitan** [EmpireProject/Empire-GUI#6]
![kali_linux-2018-06-03-20-36-59](https://user-images.githubusercontent.com/13740942/40894234-ea4c064a-676d-11e8-96e5-897f94b4e570.png)

i cant longin in the interface, can u helpme?

**Comment by dchrastil** [comment]
Although empire has 0.0.0.0 as its Host, try entering the actual IP address of your empire server. If its on your localhost, 127.0.0.1

Let me know if that works

**Comment by gearcapitan** [comment]
Thanks for your answer, I had little time but tomorrow I'll check and confirm it

**Comment by gearcapitan** [comment]
![kali_linux-2018-06-08-13-13-19](https://user-images.githubusercontent.com/13740942/41173796-cee07e5a-6b1d-11e8-8359-3c39d7905347.png)


I've tried as you mentioned but I can't log in, in the image I show the command I use to run empire

**Comment by dchrastil** [comment]
Ok, I think I see the issue. I have the port 1337 as a placeholder for that textbox, but you still need to type in 1337 to set that value. I should change that to be `<port>` or something. Try entering that manually then connecting.

**Comment by gearcapitan** [comment]
Hahahahaha! That's what it was! OMG! solved problem
